-- Extends the existing schema; it does not remove interview-preparation data.
create table public.exam_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null check (char_length(title) between 2 and 120), exam_date date, target_score numeric check (target_score between 0 and 100), weekly_study_hours integer default 7 check (weekly_study_hours between 1 and 80), status text not null default 'active' check (status in ('active','archived')), created_at timestamptz default now(), updated_at timestamptz default now());
create table public.exam_subjects (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exam_plans(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, name text not null, confidence integer default 3 check (confidence between 1 and 5), created_at timestamptz default now());
create table public.exam_chapters (id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.exam_subjects(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, name text not null, confidence integer default 3 check (confidence between 1 and 5), revision_progress numeric default 0 check (revision_progress between 0 and 100), created_at timestamptz default now());
create table public.study_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam_id uuid references public.exam_plans(id) on delete set null, topic text not null, duration_minutes integer not null check (duration_minutes between 1 and 1440), completed_at timestamptz default now());
create table public.flashcards (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam_id uuid references public.exam_plans(id) on delete set null, front text not null, back text not null, subject text, bookmarked boolean default false, created_at timestamptz default now());
create table public.practice_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam_id uuid references public.exam_plans(id) on delete set null, topic text not null, question_type text not null, score numeric, total_questions integer, correct_answers integer, duration_seconds integer, created_at timestamptz default now());
create table public.mock_tests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam_id uuid references public.exam_plans(id) on delete set null, title text not null, duration_minutes integer not null, score numeric, status text not null default 'draft' check(status in ('draft','in_progress','completed')), answers jsonb default '[]'::jsonb, created_at timestamptz default now(), completed_at timestamptz);
create table public.ai_responses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam_id uuid references public.exam_plans(id) on delete set null, tool text not null, prompt_summary text not null, response jsonb not null, created_at timestamptz default now());
create table public.readiness_reports (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, exam_id uuid references public.exam_plans(id) on delete set null, readiness_score numeric not null check(readiness_score between 0 and 100), report jsonb not null, created_at timestamptz default now());
alter table public.exam_plans enable row level security; alter table public.exam_subjects enable row level security; alter table public.exam_chapters enable row level security; alter table public.study_sessions enable row level security; alter table public.flashcards enable row level security; alter table public.practice_sessions enable row level security; alter table public.mock_tests enable row level security; alter table public.ai_responses enable row level security; alter table public.readiness_reports enable row level security;
create policy "own exam plans" on public.exam_plans for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own exam subjects" on public.exam_subjects for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own exam chapters" on public.exam_chapters for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own study sessions" on public.study_sessions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own flashcards" on public.flashcards for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own practice sessions" on public.practice_sessions for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own mock tests" on public.mock_tests for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own ai responses" on public.ai_responses for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own readiness reports" on public.readiness_reports for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
-- Force PostgREST to pick up the new tables immediately after this migration.
notify pgrst, 'reload schema';
